### ISSUE TITLE
dreamer v2 config

### ISSUE THREAD

**Issue by ptigas** [danijar/crafter#1]
Hi, 

Thank you for this environment. What would be the dreamer config for training this environment?

p.

**Comment by danijar** [comment]
Hi, thanks for your question! I just updated the baseline to match the stable release 1.0.0 of the environment and also included the scores as JSON in the repository. It's DreamerV2 with the following hparams (all other values are at the Atari default). I used a reimplementation of DreamerV2 for this but the scores with the released DreamerV2 code base should be almost the same.

```yaml
train_every: 16
rssm: {hidden: 2048, deter: 2048, stoch: 32, discrete: 32}
batch_size: 15
model_opt.lr: 1e-4
actor_opt.lr: 1e-4
critic_opt.lr: 1e-4
actor_ent: 3e-3
```
